<?php

/**
 *@file
 *The module file for SipMod
 *
 *This module modifies the checkout pane for shipping methods
 */

function sipmod_commerce_price_formatted_components_alter(&$components, $price, $entity) {
  foreach(commerce_shipping_services('flat_rate') AS $shipping_service){
    if(array_key_exists('flat_rate_'.$shipping_service['name'], $components)){
      $components['flat_rate_'.$shipping_service['name']]['title'] = t('Shipping Cost');
    }
  }

  $components['commerce_price_formatted_amount']['title'] = t('Order Total');
}